SELECT m.merchant_name,
       u.merchant_code,
       o.uid,
       u.username,
       o.user_level,
       u.currency_code,
       o.order_no,
       o.create_time,
       o.modify_time,
       o.confirm_time,
       o.remark,
       o.order_amount_total,
       o.original_order_amount_total,
       o.product_amount_total,
       o.pre_bet_amount,
       o.original_pre_bet_amount,
       o.product_count,
       o.series_type,
       o.series_value,
       o.manager_code,
       o.ac_code,
       o.ip,
       o.ip_area,
       o.device_type,
       o.device_imei,
       o.order_status,
       o.pre_settle,
       o.vip_level,
       o.lang_code,
       o.max_win_amount,
       o.original_max_win_amount,
       s.settle_amount,
       s.profit_amount,
       s.original_profit_amount,
       s.original_settle_amount,
       s.create_time settle_time,
       s.out_come,
       s.settle_type,
       s.settle_times,
       o.dangerous_id,
       o.pre_order
FROM (SELECT o1.id,
             o1.uid,
             o1.user_level,
             o1.order_no,
             o1.create_time,
             o1.modify_time,
             o1.confirm_time,
             o1.order_amount_total,
             o1.original_order_amount_total,
             o1.pre_bet_amount,
             o1.original_pre_bet_amount,
             o1.product_amount_total,
             o1.product_count,
             o1.max_win_amount,
             o1.original_max_win_amount,
             o1.series_type,
             o1.series_value,
             o1.ip,
             o1.ip_area,
             o1.device_type,
             o1.device_imei,
             o1.currency_code,
             o1.remark,
             o1.order_status,
             o1.ac_code,
             o1.manager_code,
             o1.vip_level,
             o1.lang_code,
             o1.pre_settle,
             o1.dangerous_id,
             o1.pre_order
      FROM `t_order` o1
      where o1.modify_time >= :sql_last_value
        AND o1.modify_time <= UNIX_TIMESTAMP(now()) * 1000 - 1000 * 60 * 1
      ORDER BY o1.modify_time asc
      LIMIT 150000) o
         LEFT JOIN t_settle s ON s.order_no = o.order_no and s.last_settle = 1 and s.out_come in (2, 3, 4, 5, 6) and
                                 s.bet_amount > 0
         LEFT JOIN t_user u ON u.uid = o.uid
         LEFT JOIN t_merchant m ON u.merchant_code = m.merchant_code
where u.uid is not null
  and u.merchant_code is not null
  and u.merchant_code not in ('oubao', '719919', '105627', '472028', '553452','2N12','2I859','2G325','2M175');
