select id                   as id,
       payment_cycle        as paymentCycle,
       vip_payment_cycle       vipPaymentCycle,
       technique_payment_cycle techniquePaymentCycle,
       finance_date         as financeDate,
       finance_time         as financeTime,
       merchant_id          as merchantId,
       merchant_code        as merchantCode,
       parent_id            as parentId,
       merchant_num         as merchantNum,
       merchant_name        as merchantName,
       agent_level          as agentLevel,
       currency             as currency,
       bill_amount          as billAmount,
       order_payment_amount as orderPaymentAmount,
       order_amount_total   as orderAmountTotal,
       profit_amount        as profitAmount,
       computing_standard   as computingStandard,
       terrace_rate         as terraceRate,
       execute_rate         as executeRate,
       adjust_amount        as adjustAmount,
       vip_amount           as vipAmount,
       technique_amount     as techniqueAmount,
       create_user          as createUser,
       create_time          as createTime,
       modify_user          as modifyUser,
       modify_time          as modifyTime,
       updated_time         AS updatedTime
from tybss_report.r_merchant_finance_month
WHERE (updated_time >= :sql_last_value AND updated_time < UNIX_TIMESTAMP(now()))
ORDER BY updated_time ASC LIMIT 100000;