INSERT INTO dws_report.rcs_match_order_day
SELECT concat(p.match_id,p.begin_time) AS mod_id,
       p.begin_time AS begin_time,
       p.match_id AS match_id,
       p.sport_id AS sport_id,
       p.tournament_id AS tournament_id,
       p.match_info AS match_info,
       floor(p.match_amount) AS match_amount,
       floor(p.match_settle_amount) AS match_settle_amount,
       p.match_num AS match_num,
       floor(p.match_amount - p.match_settle_amount) AS match_actual_amount,
       floor(p.live_theory_amount + p.pre_theory_amount) AS match_theory_amount,
       floor(p.match_amount - p.match_settle_amount - p.live_theory_amount + p.pre_theory_amount) AS match_profit_amount,
       nvl(cast((p.match_settle_amount/p.match_amount) * 100 As decimal(10,1)),0)  AS match_proportion,
       floor(p.live_amount) AS live_amount,
       p.live_num AS live_num,
       nvl(floor(p.live_amount/p.live_num),0) AS live_average_amount,
       nvl(round(p.live_num/p.live_user_num,1),0) AS live_average_num,
       nvl(floor(p.live_amount/p.live_user_num),0) AS live_user_amount,
       floor(p.pre_amount) AS pre_amount,
       p.pre_num AS pre_num,
       nvl(floor(p.pre_amount/p.pre_num),0) AS pre_average_amount,
       nvl(round(p.pre_num/p.pre_user_num,1),0) AS pre_average_num,
       nvl(floor(p.pre_amount/p.pre_user_num),0) AS pre_user_amount,
       floor(p.pre_two_amount) AS pre_two_amount,
       p.pre_two_num AS pre_two_num,
       nvl(floor(p.pre_two_amount/p.pre_two_num),0) AS pre_two_average_amount,
       nvl(round(p.pre_two_num/p.pre_two_user_num,1),0) AS pre_two_average_num,
       nvl(floor(p.pre_two_amount/p.pre_two_user_num),0) AS pre_two_user_amount,
       floor(p.pre_one_amount) AS pre_one_amount,
       p.pre_one_num AS pre_one_num,
       nvl(floor(p.pre_one_amount/p.pre_one_num),0) AS pre_one_average_amount,
       nvl(round(p.pre_one_num/p.pre_one_user_num,1),0) AS pre_one_average_num,
       nvl(floor(p.pre_one_amount/p.pre_one_user_num),0) AS pre_one_user_amount,
       floor(p.live_amount - p.live_settle_amount) AS live_actual_amount,
       floor(p.live_theory_amount) AS live_theory_amount,
       floor(p.live_amount - p.live_settle_amount - p.live_theory_amount) AS live_profit_amount,
       nvl(cast((p.live_settle_amount/p.live_amount) * 100 As decimal(10,1)),0) AS live_proportion,
       floor(p.pre_amount - p.pre_settle_amount) AS pre_actual_amount,
       floor(p.pre_theory_amount) AS pre_theory_amount,
       floor(p.pre_amount - p.pre_settle_amount - p.pre_theory_amount) AS pre_profit_amount,
       nvl(cast((p.pre_settle_amount/p.pre_amount) * 100 As decimal(10,1)),0) AS pre_proportion,
       floor(p.pre_two_amount - p.pre_two_settle_amount) AS pre_two_actual_amount,
       floor(p.pre_two_theory_amount) AS pre_two_theory_amount,
       floor(p.pre_two_amount - p.pre_two_settle_amount - p.pre_two_theory_amount) AS pre_two_profit_amount,
       nvl(cast((p.pre_two_settle_amount/p.pre_two_amount) * 100 As decimal(10,1)),0) AS pre_two_proportion,
       floor(p.pre_one_amount - p.pre_one_settle_amount) AS pre_one_actual_amount,
       floor(p.pre_one_theory_amount) AS pre_one_theory_amount,
       floor(p.pre_one_amount - p.pre_one_settle_amount - p.pre_one_theory_amount) AS pre_one_profit_amount,
       nvl(cast((p.pre_one_settle_amount/p.pre_one_amount) * 100 As decimal(10,1)),0) AS pre_one_proportion
FROM
  (SELECT a.begin_time,
          a.match_id,
          a.sport_id,
          a.tournament_id,
          a.match_info,
          sum(a.bet_amount) AS match_amount,
          count(1) AS match_num,
          sum(nvl(s.settle_amount,0)) AS match_settle_amount,
          sum(CASE WHEN a.match_type=2 THEN a.bet_amount ELSE 0 END) AS live_amount,
          count(case WHEN a.match_type=2 THEN 1 ELSE null END) AS live_num,
          count(distinct case WHEN a.match_type=2 THEN a.uid ELSE null END) AS live_user_num,
          sum(CASE WHEN a.match_type=1 THEN a.bet_amount ELSE 0 END) AS pre_amount,
          count(case WHEN a.match_type=1 THEN 1 ELSE null END) AS pre_num,
          count(distinct case WHEN a.match_type=1 THEN a.uid ELSE null END) AS pre_user_num,
          sum(case WHEN a.bet_time BETWEEN a.begin_time - (2 * 60 * 60 * 1000) and a.begin_time THEN a.bet_amount ELSE 0 END) AS pre_two_amount,
          count(case WHEN a.bet_time BETWEEN a.begin_time - (2 * 60 * 60 * 1000) and a.begin_time THEN 1 ELSE null END) AS pre_two_num,
          count(distinct case WHEN a.bet_time BETWEEN a.begin_time - (2 * 60 * 60 * 1000) and a.begin_time THEN a.uid ELSE null END) AS pre_two_user_num,
          sum(case WHEN a.bet_time BETWEEN a.begin_time - (1 * 60 * 60 * 1000) and a.begin_time THEN a.bet_amount ELSE 0 END) AS pre_one_amount,
          count(case WHEN a.bet_time BETWEEN a.begin_time - (1 * 60 * 60 * 1000) and a.begin_time THEN 1 ELSE null END) AS pre_one_num,
          count(distinct case WHEN a.bet_time BETWEEN a.begin_time - (1 * 60 * 60 * 1000) and a.begin_time THEN a.uid ELSE null END) AS pre_one_user_num,
          sum(case WHEN a.match_type=2 THEN nvl(s.settle_amount,0) ELSE 0 END) AS live_settle_amount,
          sum(case WHEN a.match_type=1 THEN nvl(s.settle_amount,0) ELSE 0 END) AS pre_settle_amount,
          sum(case WHEN a.bet_time BETWEEN a.begin_time - (2 * 60 * 60 * 1000) and a.begin_time THEN nvl(s.settle_amount,0) ELSE 0 END) AS pre_two_settle_amount,
          sum(case WHEN a.bet_time BETWEEN a.begin_time - (1 * 60 * 60 * 1000) and a.begin_time THEN nvl(s.settle_amount,0) ELSE 0 END) AS pre_one_settle_amount,
          sum(CASE WHEN a.match_type=2 and a.play_id IN(2,4,19,39,154,155,172,181) THEN a.bet_amount * (106 / 100 - 1) WHEN a.match_type=2 and a.play_id NOT IN(2,4,19,39,154,155,172,181) THEN a.bet_amount * (108.5 / 100 - 1) ELSE 0 END) AS live_theory_amount,
          sum(CASE WHEN a.match_type=1 THEN a.bet_amount * (103.5 / 100 - 1) ELSE 0 END) as pre_theory_amount,
          sum(case WHEN a.bet_time BETWEEN a.begin_time - (2 * 60 * 60 * 1000) and a.begin_time THEN a.bet_amount * (103.5 / 100 - 1) ELSE 0 END) AS pre_two_theory_amount,
          sum(case WHEN a.bet_time BETWEEN a.begin_time - (1 * 60 * 60 * 1000) and a.begin_time THEN a.bet_amount * (103.5 / 100 - 1) ELSE 0 END) AS pre_one_theory_amount
   FROM dwm_report.order_match_detail a
   LEFT JOIN dwm_report.t_settle_full_detail s ON a.order_no=s.order_no
   left join base_temp.bss_order o on a.order_no=o.order_no
   WHERE o.series_type=1
     AND o.order_status in (0,1)
     AND a.bet_time BETWEEN unix_timestamp(date_sub(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),1))*1000 +(12 * 60 * 60 * 1000) AND unix_timestamp(date_sub(from_unixtime(unix_timestamp(),'yyyy-MM-dd'),0))*1000 +(12 * 60 * 60 * 1000 - 1)
   GROUP BY a.match_id,
            a.match_info,
            a.sport_id,
            a.begin_time,
            a.tournament_id) p