update  admin_permission set name_en = 'Home' where id =1  ;
update  admin_permission set name_en = 'UserCenter' where id =2  ;
update  admin_permission set name_en = 'MerchantInfo' where id =3  ;
update  admin_permission set name_en = 'ChildrenManage' where id =4  ;
update  admin_permission set name_en = 'My Key' where id =5  ;
update  admin_permission set name_en = 'Player Center' where id =6  ;
update  admin_permission set name_en = 'Authorization' where id =7  ;
update  admin_permission set name_en = 'User Manage' where id =8  ;
update  admin_permission set name_en = 'Role Manage' where id =9  ;
update  admin_permission set name_en = 'Finance Report' where id =10  ;
update  admin_permission set name_en = 'Bill' where id =11  ;
update  admin_permission set name_en = 'Finance Bill' where id =12 ;
update  admin_permission set name_en = 'Report Center' where id =13  ;
update  admin_permission set name_en = 'Tickets Center' where id =14  ;
update  admin_permission set name_en = 'Merchant Report' where id =15  ;
update  admin_permission set name_en = 'Player Report' where id =16  ;
update  admin_permission set name_en = 'Message Center' where id =17  ;
update  admin_permission set name_en = 'Billboard' where id =18  ;
update  admin_permission set name_en = 'My Message' where id =19  ;
update  admin_permission set name_en = 'Match Report' where id =23  ;
update  admin_permission set name_en = 'Agent Manage' where id =24  ;
update  admin_permission set name_en = 'Order Cancel' where id =25  ;
update  admin_permission set name_en = 'Special Limit' where id =26  ;
