CREATE OR REPLACE ALGORITHM = UNDEFINED SQL SECURITY DEFINER VIEW `tybss_report`.`view_r_order_full_detail` AS SELECT
                                                                                                                                        date_format( from_unixtime(( `tor`.`create_time` / 1000 )), '%Y-%m' ) AS `dt`,
                                                                                                                                        `tor`.`order_no` AS `order_no`,
                                                                                                                                        `tor`.`uid` AS `uid`,
                                                                                                                                        `tor`.`order_status` AS `order_status`,
                                                                                                                                        `tor`.`bill_status` AS `bill_status`,
                                                                                                                                        `tor`.`product_count` AS `product_count`,
                                                                                                                                        `tor`.`series_type` AS `series_type`,
                                                                                                                                        `tor`.`series_value` AS `series_value`,
                                                                                                                                        `tor`.`product_amount_total` AS `product_amount_total`,
                                                                                                                                        `tor`.`order_amount_total` AS `order_amount_total`,
                                                                                                                                        `tor`.`device_type` AS `device_type`,
                                                                                                                                        `tor`.`ip` AS `ip`,
                                                                                                                                        `tor`.`remark` AS `remark`,
                                                                                                                                        NULL AS `tenant_id`,
                                                                                                                                        `tor`.`del_flag` AS `del_flag`,
                                                                                                                                        `tor`.`create_time` AS `create_time`,
                                                                                                                                        `tor`.`create_user` AS `create_user`,
                                                                                                                                        `tor`.`modify_user` AS `modify_user`,
                                                                                                                                        `tor`.`modify_time` AS `modify_time`,
                                                                                                                                        `tor`.`currency_code` AS `currency_code`,
                                                                                                                                        `tor`.`ip_area` AS `ip_area`,
                                                                                                                                        `tor`.`vip_level` AS `vip_level`,
                                                                                                                                        `tor`.`device_imei` AS `device_imei`,
                                                                                                                                        `tor`.`max_win_amount` AS `max_win_amount`,
                                                                                                                                        `tod`.`bet_no` AS `bet_no`,
                                                                                                                                        `tod`.`play_options_id` AS `play_options_id`,
                                                                                                                                        `tod`.`sport_id` AS `sport_id`,
                                                                                                                                        `tod`.`sport_name` AS `sport_name`,
                                                                                                                                        `tod`.`play_id` AS `play_id`,
                                                                                                                                        `tod`.`play_name` AS `play_name`,
                                                                                                                                        `tod`.`match_id` AS `match_id`,
                                                                                                                                        `tod`.`match_name` AS `match_name`,
                                                                                                                                        `tod`.`match_type` AS `match_type`,
                                                                                                                                        `tod`.`bet_time` AS `bet_time`,
                                                                                                                                        `tod`.`market_id` AS `market_id`,
                                                                                                                                        `tod`.`market_type` AS `market_type`,
                                                                                                                                        `tod`.`market_value` AS `market_value`,
                                                                                                                                        `tod`.`match_info` AS `match_info`,
                                                                                                                                        `tod`.`bet_amount` AS `bet_amount`,
                                                                                                                                        `tod`.`odds_value` AS `odds_value`,
                                                                                                                                        `tod`.`market_type_finally` AS `market_type_finally`,
                                                                                                                                        `tod`.`odd_finally` AS `odd_finally`,
                                                                                                                                        `tod`.`accept_bet_odds` AS `accept_bet_odds`,
                                                                                                                                        `tod`.`bet_status` AS `bet_status`,
                                                                                                                                        `tod`.`score_benchmark` AS `score_benchmark`,
                                                                                                                                        `tod`.`play_options` AS `play_options`,
                                                                                                                                        `tod`.`match_process_id` AS `match_process_id`,
                                                                                                                                        `tod`.`tournament_id` AS `tournament_id`,
                                                                                                                                        `tod`.`bet_result` AS `bet_result`,
                                                                                                                                        `tod`.`play_option_name` AS `play_option_name`,
                                                                                                                                        `tod`.`bet_all_result` AS `bet_all_result`,
                                                                                                                                        `tod`.`settle_score` AS `settle_score`,
                                                                                                                                        `tu`.`fake_name` AS `username`,
                                                                                                                                        `tu`.`user_level` AS `user_level`,
                                                                                                                                        `tu`.`ip_address` AS `ip_address`,
                                                                                                                                        `tu`.`create_time` AS `user_create_time`,
                                                                                                                                        `tm`.`merchant_code` AS `merchant_code`,
                                                                                                                                        `tm`.`id` AS `merchant_id`,
                                                                                                                                        `tm`.`merchant_name` AS `merchant_name`,
                                                                                                                                        `tm`.`level` AS `level`,
                                                                                                                                        `tm`.`parent_id` AS `parent_id`,
                                                                                                                                        `tm`.`create_time` AS `merchant_create_time`,
                                                                                                                                        `tm`.`agent_level` AS `agent_level`,
                                                                                                                                        `tm`.`currency` AS `merchant_currency`,
                                                                                                                                        `tm`.`rate` AS `rate`,
                                                                                                                                        NULL AS `first_bet_date`,
                                                                                                                                        date_format( from_unixtime(( `tor`.`create_time` / 1000 )), '%Y-%m-%d %H:%m:%s' ) AS `sync_time`
                                                                                                                                    FROM
                                                                                                                                        (((
                                                                                                                                            `tybss_merchant_common`.`t_order` `tor`
                                                                                                                                                LEFT JOIN `tybss_merchant_common`.`t_order_detail` `tod` ON ((
                                                                                                                                                    `tor`.`order_no` = `tod`.`order_no`
                                                                                                                                                )))
                                                                                                                                            LEFT JOIN `tybss_merchant_common`.`t_user` `tu` ON ((
                                                                                                                                                    `tu`.`uid` = `tod`.`uid`
                                                                                                                                                )))
                                                                                                                                            LEFT JOIN `tybss_merchant_common`.`t_merchant` `tm` ON ((
                                                                                                                                                `tm`.`merchant_code` = `tu`.`merchant_code`
                                                                                                                                            )));
