CREATE TABLE `t_merchant_config` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT ''逻辑id'',
  `merchant_code` varchar(225) COLLATE utf8mb4_0900_as_cs NOT NULL COMMENT ''商户编码'',
  `profes_tag` tinyint(4) NOT NULL DEFAULT ''1'' COMMENT ''专业版 1 白色 2黑色'',
  `nocice_tag` tinyint(4) NOT NULL DEFAULT ''1'' COMMENT ''新手版 1 白色 2黑色'',
  `standard_tag` tinyint(4) NOT NULL DEFAULT ''2'' COMMENT ''标准版 1 白色 2黑色'',
  `title` varchar(1000) COLLATE utf8mb4_0900_as_cs DEFAULT NULL COMMENT ''标题'',
  `dark_logo_url` varchar(255) COLLATE utf8mb4_0900_as_cs DEFAULT NULL COMMENT ''深色log地址'',
  `white_logo_url` varchar(255) COLLATE utf8mb4_0900_as_cs DEFAULT NULL COMMENT ''白色log地址'',
  `pc_logo_url` varchar(255) COLLATE utf8mb4_0900_as_cs DEFAULT NULL COMMENT ''pc浏览器图标'',
  `compat_logo_url` varchar(255) COLLATE utf8mb4_0900_as_cs DEFAULT NULL COMMENT ''兼容性log'',
  `video_logo_url` varchar(255) COLLATE utf8mb4_0900_as_cs DEFAULT NULL COMMENT ''视频log'',
  `logo_enable` tinyint(4) DEFAULT ''0'' COMMENT ''logo控制 0 禁用 1启用'',
  `inline_width` bigint(10) DEFAULT NULL COMMENT ''内嵌版最大宽度 1200-1480px'',
  `pc_video_background` varchar(255) COLLATE utf8mb4_0900_as_cs DEFAULT NULL COMMENT ''pc视频播放背景'',
  `h5_default` tinyint(4) NOT NULL DEFAULT ''1'' COMMENT ''h5默认板式 1白色 2深色'',
  `app_default` tinyint(4) NOT NULL DEFAULT ''1'' COMMENT ''app 默认版式 1白色 2深色'',
  `market_default` tinyint(4) DEFAULT ''1'' COMMENT ''默认盘口赔率 1 欧洲盘 2香港盘'',
  `create_time` datetime DEFAULT NULL COMMENT ''创建时间'',
  `create_user` varchar(255) COLLATE utf8mb4_0900_as_cs DEFAULT NULL COMMENT ''创建人'',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT ''修改时间'',
  `update_user` varchar(255) COLLATE utf8mb4_0900_as_cs DEFAULT NULL COMMENT ''更新人'',
  PRIMARY KEY (`id`),
  UNIQUE KEY `merchantCode_idx` (`merchant_code`) USING BTREE COMMENT ''商户编码唯一索引''
) ENGINE=InnoDB AUTO_INCREMENT=776 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_as_cs;